# Day 27
# to take username, password, hosts from group_vars->all.yaml file instead of taking from inventory.ini file.

ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-{{ env }}.vardevops.online
REDIS_HOST: redis-{{ env }}.vardevops.online
MYSQL_HOST: mysql-{{ env }}.vardevops.online
RABBITMQ_HOST: rabbitmq-{{ env }}.vardevops.online
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.vardevops.online
USER_HOST: user.backend-alb-{{ env }}.vardevops.online
CART_HOST: cart.backend-alb-{{ env }}.vardevops.online
SHIPPING_HOST: shipping.backend-alb-{{ env }}.vardevops.online
PAYMENT_HOST: payment.backend-alb-{{ env }}.vardevops.online
app_version: v3