; Day 27

[local]
localhost

[mongodb]
localhost

[catalogue]
catalogue-dev.vardevops.online

[redis]
localhost

[user]
user-dev.vardevops.online

[cart]
cart-dev.vardevops.online

[mysql]
mysql-dev.vardevops.online

[shipping]
shipping-dev.vardevops.online

[rabbitmq]
rabbitmq-dev.vardevops.online

[payment]
payment-dev.vardevops.online

[frontend]
frontend-dev.vardevops.online